### ISSUE TITLE
[Bug] - when opening a C++ file, it take at least 5 seconds until the color appear. 

### ISSUE THREAD

**Issue by duduarbel** [dinbtechit/vscode-theme#48] opened 2022-12-28 14:16 UTC
## Describe the bug
when opening a C++ file, it take at least 5 seconds until the color appear. 

## Platform & Language Details (please complete the following information):
- Platform: clion
- Platform Version: 2022.3.1
- Language:C++
- Version: of what?
- 
## Additional context/Logs
OS: Manjaro
Machine: very strong

**Comment by dinbtechit** [comment] 2022-12-28 14:39
Wondering if this could be related to insufficient memory.

Can you send me the following details?  To see how much memory and list of plugins your IDE is using.

1. Double press the  `shift` key (to bring the Search everywhere window ) 
2. Search for `About` ->  Click the `Copy`  and Paste the details here.

**Comment by duduarbel** [comment] 2022-12-28 14:44
CLion 2022.3.1
Build #CL-223.8214.51, built on December 20, 2022
Licensed to qSpark LLC / Dudu Arbel
You have a perpetual fallback license for this version.
Subscription is active until December 18, 2023.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.84-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
    run.processes.with.pty=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.2)
    com.github.dinbtechit.vscodetheme (1.7.6)

Current Desktop: GNOME

**Comment by dinbtechit** [comment] 2022-12-28 15:18
Interesting... You seem to have ample memory and cores there. 

Strangely, I can't reproduce the issue on my machine. It's almost instantaneous on mine. I am assuming you don't have that issue with one dark theme?

https://user-images.githubusercontent.com/17984781/209832740-5fe72ef2-4ce7-40af-99d6-07ff2d4b9815.mp4


```
CLion 2022.3.1
Build #CL-223.8214.51, built on December 20, 2022
Runtime version: 17.0.5+1-b653.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Metal Rendering is ON
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.github.dinbtechit.vscodetheme (1.7.6)
```

**Comment by duduarbel** [comment] 2022-12-28 16:11
No.
It works fine on any other scheme I had tried

**Comment by duduarbel** [comment] 2022-12-29 14:52
hi DInesh, how are you?

If I look at 'Dark' color scheme - the xml size inside it is 4k
Your VSCode xml size is almost 30k
Maybe that is the cause of the problem?

BTW - this happens on a small file, and is much worse on my big project. it
take 10 seconds to paint the file - far to long to be useful.

What else can be done?
Thanks
Dudu

**Comment by dinbtechit** [comment] 2022-12-29 15:16
Hi! That shouldn't cause any issues at all. 30k is still tiny. This seems to be specific to your laptop setup. (That's very unfortunate). At this moment, it's hard to triage this without being able to reproduce the issue. I even tried it on my ubuntu machine (slightly less powerful than my MacBook. It worked fine).

Also, this is the first issue related to performance in 100k downloads as far as I can tell this does not seem to be affecting a larger audience. 

Are you using a SSDs storage? Also are you able to post a video? (I don't know how far that will be helpful but wouldn't hurt to have more info.)

**Comment by dannylol19** [comment] 2023-01-13 05:34
@duduarbel this could be the IDE indexing your project.
When the issue occurs, check if the bottom right status says something like "indexing...". This is not a problem with the color scheme, it is the IDE figuring out what is a function and what is a class etc...

**Comment by dinbtechit** [comment] 2023-01-20 17:33
I am closing this issue as there are no further updates from the user. Please feel free to reopen it with more details - such as video, logs, etc.

**Closed by dinbtechit** 2023-01-20 17:33 UTC
Labels: bug
