### ISSUE TITLE
[Bug] - Stop messing with my config

### ISSUE THREAD

**Issue by castrosu** [dinbtechit/vscode-theme#69] opened 2023-06-23 19:28 UTC
People and me just want the colors itself not a thing that changes the entire config of the IDE, if I wanted to mess with my IDE and wanted the cool colors I would have changed to VS Code a long time ago

**Comment by dinbtechit** [comment] 2023-06-23 19:55
I am not sure what do you mean by "changes the entire config of the IDE"? This is just a theme plugin and we don't modify your existing settings of any sort.

> On a side note - this forum will not tolerate any abusive behaviour. I certainly welcome constructive feedback as we are one community and trying to help each other. You can always uninstall it if you don't like the plugin. This plugin is completely open source so you can fork and modify it in any way you want.

**Comment by castrosu** [comment] 2023-06-23 21:28
![image](https://github.com/dinbtechit/vscode-theme/assets/41306496/20cd74cd-b165-45cd-a9ab-13b9f45f6d4d)
maybe showing non project files in the problems tab is a thing that happens only when I install your theme

**Comment by dinbtechit** [comment] 2023-06-23 21:41
Interesting... That looks like a typescript error that has nothing to do with this plugin at all. There is no code in the theme that would do that. Just curious, when you uninstall the VScode theme those errors go away?

**Comment by castrosu** [comment] 2023-06-25 14:17
Yes they do, that's the weird part also if I change the imports color in javascript the colors automatically change like they are stuck to that value/color

**Comment by castrosu** [comment] 2023-06-25 14:35
And also the problems if you see on the left it has project wide problems disabled so it shouldn't even appear

**Comment by dinbtechit** [comment] 2023-06-25 14:57
Changing colors through settings is not fully supported yet. So they may not work as expected. I am trying to find a way to make that work with all versions of IDEs which is a bit of a challenge at the moment.

But for triaging the issue that you are referring to - can you provide some more information? 

1. What Jetbrains IDE flavor are you using? and the version of the IDE (You can also go to Help -> about -> copy and paste the information here.)
2.  Can you provide some the screen recording of what it looks with and without the VSCode theme plugin?

**Comment by castrosu** [comment] 2023-06-27 08:17
> Changing colors through settings is not fully supported yet. So they may not work as expected. I am trying to find a way to make that work with all versions of IDEs which is a bit of a challenge at the moment.
> 
> But for triaging the issue that you are referring to - can you provide some more information?
> 
> 1. What Jetbrains IDE flavor are you using? and the version of the IDE (You can also go to Help -> about -> copy and paste the information here - this is more helpful to know what other plugins you are using.)
> 2. Can you provide some screen recording of what it looks with and without the VSCode theme plugin?

I will try to make some sort of recording so I can show you, I am just saying changing the editor color or the code scheme, when trying to use another color or when trying to disable the "inherit" option it removes but automatically ticks the box of inherit again, why is that? I can't tell if it's a me thing or not but I have tried to use this theme multiple times in the past but it always gave me weird IDE bugs like errors appearing like the one I sent in the screenshot, me wanting to change the editor colors but it always came back, at some time I remembered it to change my icons size on the toolbar and on the whole ui in general but not the top bar

**Comment by dinbtechit** [comment] 2023-06-27 20:32
> I am just saying changing the editor color or the code scheme, when trying to use another color or when trying to disable the "inherit" option it removes but automatically ticks the box of inherit again, why is that? 

I have no clue what you are talking about. Please provide screenshots and more details of what you're trying to do. Although this sounds like a separate issue altogether.


>  I can't tell if it's a me thing or not but I have tried to use this theme multiple times in the past but it always gave me weird IDE bugs like errors appearing like the one I sent in the screenshot, me wanting to change the editor colors but it always came back, at some time I remembered it to change my icons size on the toolbar and on the whole ui in general but not the top bar

This plugin does not modify any of that. The screenshot that you showed me earlier is a typescript error that has NOTHING to do with this plugin. I don't know how else to explain this to you. If you don't want to believe me you can check the code yourself.  

This plugin will not change any of the icon sizes as well.... there is no code in this plugin that will do that. I just feel like you are blaming all the issues on the VSCode plugin, which is completely unfair and baseless.  If you still think it is the VSCode theme plugin that causes all of that, provide me video evidence. 

**Also as I asked you earlier, please provide more details about the your IDE:**

1. Go to about Intellij or what ever IDE that you are using:
![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/0c743b37-2618-463f-b401-ea3763615af4)

2. Copy and paste the details here:
![image](https://github.com/dinbtechit/vscode-theme/assets/17984781/d51e4d2f-033f-405c-bb58-971a499bd089)

**Comment by castrosu** [comment] 2023-06-27 22:01
> > I am just saying changing the editor color or the code scheme, when trying to use another color or when trying to disable the "inherit" option it removes but automatically ticks the box of inherit again, why is that?
> 
> I have no clue what you are talking about. Please provide screenshots and more details of what you're trying to do. Although this sounds like a separate issue altogether.
> 
> > I can't tell if it's a me thing or not but I have tried to use this theme multiple times in the past but it always gave me weird IDE bugs like errors appearing like the one I sent in the screenshot, me wanting to change the editor colors but it always came back, at some time I remembered it to change my icons size on the toolbar and on the whole ui in general but not the top bar
> 
> This plugin does not modify any of that. The screenshot that you showed me earlier is a typescript error that has NOTHING to do with this plugin. I don't know how else to explain this to you. If you don't want to believe me you can check the code yourself.
> 
> This plugin will not change any of the icon sizes as well.... there is no code in this plugin that will do that. I just feel like you are blaming all the issues on the VSCode plugin, which is completely unfair and baseless. If you still think it is the VSCode theme plugin that causes all of that, provide me video evidence.
> 
> **Also as I asked you earlier, please provide more details about the your IDE:**
> 
> 1. Go to about Intellij or what ever IDE that you are using:
>    ![image](https://user-images.githubusercontent.com/17984781/249275495-0c743b37-2618-463f-b401-ea3763615af4.png)
> 2. Copy and paste the details here:
>    ![image](https://user-images.githubusercontent.com/17984781/249275089-d51e4d2f-033f-405c-bb58-971a499bd089.png)

IntelliJ IDEA 2023.1.3 (Ultimate Edition)
Build #IU-231.9161.38, built on June 20, 2023
Licensed to [removed]
Subscription is active until [removed].
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.github.copilot (1.2.9.2684)
    com.markskelton.one-dark-theme (5.8.0)
    com.intellij.plugins.vscodekeymap (231.8109.91)
    com.jetbrains.plugins.jade (231.8109.91)
    izhangzhihao.rainbow.brackets (2023.2.11)
    com.github.dinbtechit.vscodetheme (1.8.1)
    com.mallowigi (90.0.0)
    zielu.gittoolbox (500.0.10+213)

Kotlin: 231-1.8.21-IJ9161.38

**Comment by dinbtechit** [comment] 2023-06-28 15:21
None of the issues described in this ticket is be caused by the VSCode theme plugin. I see you have other theme plugins installed perhaps it is coming from them? Closing this ticket.

**Closed by dinbtechit** 2023-06-28 15:21 UTC
Labels: bug
