### ISSUE TITLE
[Bug] java.lang.Throwable: Expected to set [null,null,0,BOXED,null,{},null] but actual attributes are: [java.awt.Color[r=103,g=183,b=164],null,0,BOXED,null,{},null]; colorsScheme: '_@user_Xcode Dark'; highlighter:RangeHighlighter: (1852,1861); layer:3000; tooltip: HighlightInfo(1852,1861) text='tokenizer'; severity=INFORMATION; group=4 (class com.intellij.openapi.editor.impl.RangeHighlighterImpl); was reused from the bin: false; is being recycled: false; markup: MarkupModel for DocumentImpl[VirtualFile: /home/vlasdas/local/code/apparat/notebooks/testing.ipynb] (class com.intellij.openapi.editor.impl.MarkupModelImpl); attributes after the second .setAttributes(): [null,null,0,BOXED,null,{},null] (set successfully)

### ISSUE THREAD

**Issue by noirsender** [dinbtechit/vscode-theme#177] opened 2024-01-13 23:38 UTC
#Describe the bug

#To Reproduce

#Expected behavior

#Screenshots

#Environment
* Java: JetBrains s.r.o. 17.0.9
* OS: Linux amd64
* IDE: PyCharm 2023.3.2
* Version: 1.10.7

#Additional context

#Stacktrace#
 
```
java.lang.Throwable: Expected to set [null,null,0,BOXED,null,{},null] but actual attributes are: [java.awt.Color[r=103,g=183,b=164],null,0,BOXED,null,{},null]; colorsScheme: '_@user_Xcode Dark'; highlighter:RangeHighlighter: (1852,1861); layer:3000; tooltip: HighlightInfo(1852,1861) text='tokenizer'; severity=INFORMATION; group=4 (class com.intellij.openapi.editor.impl.RangeHighlighterImpl); was reused from the bin: false; is being recycled: false; markup: MarkupModel for DocumentImpl[VirtualFile: /home/vlasdas/local/code/apparat/notebooks/testing.ipynb] (class com.intellij.openapi.editor.impl.MarkupModelImpl); attributes after the second .setAttributes(): [null,null,0,BOXED,null,{},null] (set successfully)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.codeInsight.daemon.impl.BackgroundUpdateHighlightersUtil.createOrReuseHighlighterFor(BackgroundUpdateHighlightersUtil.java:319)
	at com.intellij.codeInsight.daemon.impl.BackgroundUpdateHighlightersUtil.addHighlighterToEditorIncrementally(BackgroundUpdateHighlightersUtil.java:74)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.addInfoIncrementally(HighlightingSessionImpl.java:202)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightInfoProcessor.infoIsAvailable(DefaultHighlightInfoProcessor.java:160)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.queueInfoToUpdateIncrementally(GeneralHighlightingPass.java:498)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$1.add(GeneralHighlightingPass.java:483)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor$1.queueToUpdateIncrementally(DefaultHighlightVisitor.java:84)
	at com.intellij.codeInsight.daemon.impl.B.create(B.java:318)
	at com.github.dinbtechit.vscodetheme.annotators.BaseAnnotator.annotate(BaseAnnotator.kt:26)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:128)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:106)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:361)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$7(GeneralHighlightingPass.java:292)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:321)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$8(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:91)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:324)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:287)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:234)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:80)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by dinbtechit** [comment] 2024-01-13 23:42
@noirsender - Thank you for reporting the issue. Are you able to provide a sample repo to reproduce this issue?

**Comment by noirsender** [comment] 2024-01-13 23:56
I am sorry I am working locally on pycharm and have no clue how the issue
showed up. Nevertheless, pycharm kept working like a charm, didn't even
have to restart.

**Comment by dinbtechit** [comment] 2024-01-13 23:57
oh ok.. This issue has been reported couple of times but I have no idea how to recreate this issue as I am not a python developer. Closing as unable to reproduce

**Closed by dinbtechit** 2024-01-13 23:57 UTC
